import numpy as np
array = []
with open("trafficmotion.txt", "r") as f:
    array = f.read().split(",")
    results = list(map(float, array))
    traffic = np.asarray(results)
    #print ("1:" + str(len(results)))
with open("interviewmotion.txt", "r") as f:
    array = f.read().split(",")
    results = list(map(float, array))
    interview = np.asarray(results)
    #print ("2:" + str(len(results)))
with open("flowersmotion.txt", "r") as f:
    array = f.read().split(",")
    results = list(map(float, array))
    flowers = np.asarray(results)
    #print ("3:" + str(len(results)))
with open("sportsmotion.txt", "r") as f:
    array = f.read().split(",")
    results = list(map(float, array))
    sports = np.asarray(results)
    #print ("4:" + str(len(results)))
with open("starcraftmotion.txt", "r") as f:
    array = f.read().split(",")
    results = list(map(float, array))
    starcarft = np.asarray(results)
    #print ("5:" + str(len(results)))
with open("moviemotion.txt", "r") as f:
    array = f.read().split(",")
    results = list(map(float, array))
    movie = np.asarray(results)
    #print ("6:" + str(len(results)))
with open("musicvideomotion.txt", "r") as f:
    array = f.read().split(",")
    results = list(map(float, array))
    musicvideo = np.asarray(results)
    #print ("7:" + str(len(results)))
with open("Q4.txt", "r") as f:
    array = f.read().split(",")
    results = list(map(float, array))
    query = np.asarray(results)
    #print ("8:" + str(len(results)))
traffic_array = np.zeros((451))
interview_array = np.zeros((451))
flowers_array = np.zeros((451))
sports_array = np.zeros((451))
starcarft_array = np.zeros((451))
movie_array = np.zeros((451))
musicvideo_array = np.zeros((451))
for i in range(451):
    musicvideo_array[i] = np.sum(np.absolute(np.subtract(musicvideo[i:i+149],query)))
    traffic_array[i] = np.sum(np.absolute(np.subtract(traffic[i:i+149],query)))
    interview_array[i] = np.sum(np.absolute(np.subtract(interview[i:i+149],query)))
    flowers_array[i] = np.sum(np.absolute(np.subtract(flowers[i:i+149],query)))
    sports_array[i] = np.sum(np.absolute(np.subtract(sports[i:i+149],query)))
    starcarft_array[i] = np.sum(np.absolute(np.subtract(starcarft[i:i+149],query)))
    movie_array[i] = np.sum(np.absolute(np.subtract(movie[i:i+149],query)))
print ("music motion change:     " + str(np.amin(musicvideo_array)))
print ("traffic motion change:   " + str(np.amin(traffic_array)))
print ("flowers motion change:   " + str(np.amin(flowers_array)))
print ("sports motion change:    " + str(np.amin(sports_array)))
print ("starcraft motion change: " + str(np.amin(starcarft_array)))
print ("interview motion change: " + str(np.amin(interview_array)))
print ("movie motion change:     " + str(np.amin(movie_array)))
